accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name='accounts'
urlpatterns=[
    path('',views.home,name="home"),
    path('register/',views.register,name="create_user"),
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'),name='logout')
]

userAuth/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('accounts.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location= models.CharField(max_length=500)
    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms    
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
class UserForm(UserCreationForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields= ['username','email','password1','password2']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def register(request):
    if request.method=='POST':
        form=UserForm(request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            form.save()
            messages.success(request,f'form submitted with name {username}')
            return redirect('accounts:create_user')
    else:
        form=UserForm()
    return render(request,'accounts/register.html',{'form':form})

@login_required
def home(request):
    return render(request,'accounts/profile.html',{})

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>

    <nav class="navbar bg-dark navbar-expand-lg " style="width: 100%;" data-bs-theme="dark">
        <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'accounts:home' %}">DJangoUserAuth</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        {% if not user.is_authenticated %}
        
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:create_user' %}">Register</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">logout</a>
          </li>
          {% endif %}
   
      </ul>
    </div>
  </div>
</nav>
    {% block body%}
    {% endblock %}

</body>
</html>

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block body %}
    <!-- {% if messages %}
    {% for message in messages %}

    <div class="alert alert-{{ message.tags }}">
        
    {{message}}
    </div>
    {% endfor%}
    {% endif %} -->

<div class="d-flex justify-content-center pt-4">
    <form method="post" class="" >
    {% csrf_token %}
    {{form}}
    <button type="submit">submit</button>
</form>
</div>

{% endblock%}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}
{% block body %}
<div class="name">

hello {{user.username}}
</div>


<img width="100px" height="100px" src="{{ user.profile.image.url }}" alt="">
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% block body %}
{% if messages %}
{% for message in messages %}

<div class="alert alert-{{ message.tags }}">
     
{{message}}
</div>
{% endfor%}
{% endif %}

<div class="d-flex justify-content-center pt-4">
        <form method="post" class="" >
        {% csrf_token %}
        <!-- {{form}} -->
        {% for field in form %}
            <div class="form-group">
                {{field.name}}:
                {{field}}
            </div>
            {% if field.errors %}
            <div class="error-message">
                {% for error in field.errors %}
                    {{ error }}
                {% endfor %}
            </div>
        {% endif %}
        {% endfor %}
        <button class="btn btn-success " type="submit">submit</button>
    </form>
</div>

{% endblock%}